### ISSUE TITLE
Add into_stream for async Receivers

### ISSUE THREAD

**Issue by Ten0** [qingstor/crossfire-rs#3]
Crossbeam-channel's Receiver has `into_iter()`. Similarly, we could have into_stream for async receivers.
It looks like this could be used: https://docs.rs/futures/0.3.5/futures/stream/fn.unfold.html

**Comment by frostyplanet** [comment]
Ok, that can be done

**Comment by frostyplanet** [comment]
https://github.com/qingstor/crossfire-rs/commit/eb8922e595d452915c06ac35582be8051b3360c9

will release version 0.1.4
